## Numerical Computing with Python and Numpy

In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [2]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights = [w1, w2, w3]

We can now write a function crop_yield to calculate the yield of apples (or any other crop) given the climate data and the respective weights.

In [3]:
# This code loops through two lists simultaneously, pairing elements from region and weights together.
for x, w in zip(kanto, weights):
    print(x, w)

73 0.3
67 0.2
43 0.5


In [4]:
def crop_yield(region, weights):
    results = 0
    for x, w in zip(region, weights):
        results += x*w
    return results

In [5]:
crop_yield(kanto, weights)

56.8

In [6]:
import numpy as np

In [7]:
kanto = np.array([73, 67, 43])
weights = np.array([w1, w2, w3])

In [8]:
# ndarray -> n-dimentions of array
type(kanto)

numpy.ndarray

Just like lists, Numpy arrays support the indexing notation []

In [9]:
print(weights[0])
print(kanto[2])

0.3
43


## Operating on Numpy arrays  

We can now compute the dot product of the two vectors using the `np.dot` function.

In [10]:
np.dot(kanto, weights)

np.float64(56.8)

We can achieve the same result with lower level operations supported by Numpy arrays:  

Performing an element-wise multiplication and calculating the sum of the resulting numbers.

In [11]:
(kanto * weights).sum()

np.float64(56.8)

The `*` operator performs an element-wise multiplication of two arrays (assuming they have same size), and the sum method calculate the sum of numbers in an array.

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1*arr2)

[ 4 10 18]


**Benefits of Using Numpy arrays**  

- **Ease of Use**
- **Perfomance**

In [13]:
# Python lists
arr1 = list(range(100000))
arr2 = list(range(100000, 200000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [14]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 32.4 ms, sys: 1.79 ms, total: 34.1 ms
Wall time: 37.7 ms


833323333350000

In [15]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 256 μs, sys: 0 ns, total: 256 μs
Wall time: 267 μs


np.int64(833323333350000)

Using **np.dot** is 100 times faster than using a for loop  
- This makes Numpy especially useful while working with really large datasets with tens os thousands or millions of data points.

## Multi-dimesional Numpy arrays  

We can now go one step further, and represent the climate data for all the regions together using a single 2-dimensional Numpy array

In [16]:
climate_data = np.array([
    [73, 67, 43],
    [91, 88, 64], 
    [102, 43, 37],
    [69, 96, 70]
])

In [17]:
type(climate_data)

numpy.ndarray

Numpy arrays can have any number of dimesions, and different lengths along each dimesion  

We can inspect the length along each dimesion using the `.shape` property of an array.

In [22]:
# 2D array
climate_data.shape

(4, 3)

In [23]:
# 3D array
arr3 = np.array([
    [[11, 12, 13],
    [13, 14, 15]],
    [[15, 16, 17],
    [17, 18, 19.5]]
])

In [27]:
arr3.shape

(2, 2, 3)

All the elements in a numpy array have the same datatype. You check the data type of an array using the `.dtype` property.

In [28]:
weights.dtype

dtype('float64')

In [29]:
climate_data.dtype

dtype('int64')

If an array contains even a single floating point number, all the other elements are also converted to floats.

We can now compute the predicted yields of apples in all the regions, using a single matrix multiplication between climate_data (a 5 by 3 matrix) and weights (a vector of length 3)  

We can use the `np.matmul` function from Numpy, or simply use the `@` operator to perform matrix multiplication.

In [30]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 57.7, 74.9])

In [31]:
climate_data @ weights

array([56.8, 76.9, 57.7, 74.9])

## Working with CSV data files  

Numpy also provides helper functions reading & writing to files  

To read this file into a numpy array. we can use the `genfromtxt` function.

In [36]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_data

array([[ 25.  ,  76.  ,  99.  ],
       [ 39.  ,  65.  ,  70.  ],
       [ 67.  ,  20.99,  28.  ],
       [ 11.23,  12.67,  13.9 ],
       [ 13.  ,  14.55,  15.45],
       [102.  ,  43.55,  37.09],
       [ 73.09,  67.88,  43.89],
       [ 91.55,  88.34,  64.87]])

In [ ]:
climate_data.shape  

(8, 3)