# WhatsApp Data Analysis and AI journey

## What is Numpy?  
- Numpy Numerical Python is a powerful Python library used for working with numbers and arrays.

## Why Use Numpy?
- Python lists work well, but Numpy arrays are much faster for mathematical operations
- Numpy is used for:
1. Data Analysis
2. Machine Learning
3. Data Visualization
4. Scientific Computing

In [1]:
# Importing the library
import numpy as np

In [2]:
# Creating numpy arrays
numbers = np.array([10, 20, 30, 40])
print(numbers)

[10 20 30 40]


In [4]:
# Check Array Properties
print(numbers.ndim) # Number of dimentions
print(numbers.size) # Total number of elements
print(numbers.shape) # Structure of the array

1
4
(4,)


In [5]:
# Accessing Array Elements
print(numbers[0])
print(numbers[2])

10
30


In [6]:
# Array Slicing
print(numbers[1:4])

[20 30 40]


In [7]:
# Basic Array Operations
print(numbers + 5)
print(numbers * 2)

[15 25 35 45]
[20 40 60 80]


- Numpy performs operations on every element at once (elementwise operation)

In [10]:
# Print the first and last element
print(numbers[-1])
print(numbers[0])

# Add 100 to every element
print(numbers + 100)

40
10
[110 120 130 140]


## Master 2D Arrays, Reshaping & Mathematical Functions  

### What is a 2D Array?
- A 2D array stores data in rows and columns, just like a table or spreadsheet

In [11]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(matrix)

[[10 20 30]
 [40 50 60]]


In [13]:
# Check Array Shape
# Use the .shape attribute to find the dimensions of an array

print(matrix.shape) # 2 row and 3 columns

(2, 3)


In [14]:
# Reshape an Array
# Convert a 1D array into a 2D array using .reshape()
numbers = np.array([1, 2, 3, 4, 5, 6])

new_array = numbers.reshape(2, 3)
print(new_array)

[[1 2 3]
 [4 5 6]]


- The total number of elements must remain the same

## Mathematical Functions
- NumPy provides built-in functions for calculations

In [15]:
numbers = np.array([10, 20, 30, 40])

print(np.sum(numbers))
print(np.mean(numbers))

100
25.0


In [16]:
# Minimum and Maximum Values
numbers = np.array([25, 10, 45, 30])

print(np.min(numbers))
print(np.max(numbers))

10
45


In [17]:
# Mean, Median & Standard Deviation
# These are common statistical calculations
numbers = np.array([10, 20, 30, 40])

print(np.mean(numbers)) # Average value
print(np.median(numbers)) # Middle value after sorting
print(np.std(numbers)) # Measures how spread out the values are

25.0
25.0
11.180339887498949


In [18]:
matrix.size

6

## Indexing, Slicing, Boolean Indexing and Filtering
- One of the biggest advantages of NumPy is how quickly you can access and filter data.

### Array Indexing
- Indexing is used to access a specific element in an array.

In [2]:
import numpy as np
numbers = np.array([10, 20, 30, 40, 50, 60])

# Indexing starts from 0
print(numbers[0])
print(numbers[3])

10
40


### Array Slicing
- Slicing extracts a portion of an array

In [4]:
print(numbers[1:5])
print(numbers[:3])
print(numbers[3:])
print(numbers[-2:])

[20 30 40 50]
[10 20 30]
[40 50 60]
[50 60]


### Indexing in 2D Arrays
- Access elements using row and column indexes.

In [5]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix[1, 2])

60


In [6]:
# Access an entire row:
print(matrix[0])

# Access an entire column
print(matrix[:, 1])

[10 20 30]
[20 50 80]


### Boolean Indexing
- Boolean indexing selects elements that satisfy a condition.

In [8]:
numbers = np.array([12, 25, 8, 40, 15])
print(numbers > 20)

[False  True False  True False]


### Filtering Data
- Use Boolean indexing to filter values.

In [9]:
print(numbers[numbers > 20])

[25 40]


In [11]:
print(numbers[numbers % 2 == 0])

[12  8 40]


### Multiple Conditions
- Filter using more than one condition.

In [12]:
numbers = np.array([12, 25, 8, 40, 15, 30])
result = numbers[(numbers >= 15) & (numbers <= 30)]
print(result)

[25 15 30]


## Sorting, Searching, Stacking & Spliting Arrays  

### Sorting Arrays
- Numpy provides the **sort()** functions to sort array elements in ascending order.

In [12]:
import numpy as np

numbers = np.array([40, 10, 30, 20])

print(np.sort(numbers))

[10 20 30 40]


### Searching Elements
- Use **where()** to find the index of an element.

In [4]:
numbers = np.array([10, 20, 30, 20, 40])

print(np.where(numbers == 20))

(array([1, 3]),)


This means the value 20 is present at index 1 and 3.

### Stacking Arrays Vertically
- Combine arrays column-wise using **vstack()**.

In [6]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# combines two arrays row-wise
print(np.vstack((array1, array2)))

[[1 2 3]
 [4 5 6]]


### Stacking Arrays Horizontally
- Combine arrays column-wise using **hstack()**.

In [7]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(np.hstack((array1, array2)))

[1 2 3 4 5 6]


### Splitting Arrays
- Use **split()** to divide an array into equal parts.

In [8]:
numbers = np.array([10, 20, 30, 40, 50, 60])

print(np.split(numbers, 3))

[array([10, 20]), array([30, 40]), array([50, 60])]


### Copy vs View
#### Copy
- Changes to the original array do not affect the copied array.

In [9]:
numbers = np.array([10, 20, 30])

copy_array = numbers.copy()

numbers[0] = 100

print(copy_array)
print(numbers)

[10 20 30]
[100  20  30]


#### View
- A view shares the same data as the original array.

In [10]:
numbers = np.array([10, 20, 30])

view_array = numbers.view()

numbers[0] = 100
print(view_array)

[100  20  30]


### Find Unique Values
- Use **unique()** to remove duplicate values.

In [13]:
numbers = np.array([10, 20, 20, 30, 30, 40])
print(np.unique(numbers))

[10 20 30 40]


In [16]:
# Find Index of a specific value
print(np.where(numbers == 20))

(array([1, 2]),)


## Random Numbers, Matrix Operations & Saving Arrays
### Random Number Generation
- NumPy provides the 'random' module to generate random values

In [18]:
import numpy as np
number = np.random.randint(1, 101)
print(number)

19


In [19]:
# Generate Multiple Random Numbers
numbers = np.random.randint(1, 11, size=5)
print(numbers)

[ 1  6  7 10  2]


### Create a Matrix
- A matrix is a two-dimensional NumPy array.

In [22]:
matrix = np.array([
    [1, 2],
    [3, 4]
])
print(matrix)
print('This is a {} matrix'.format(matrix.shape))

[[1 2]
 [3 4]]
This is a (2, 2) matrix


### Transpose of a Matrix
- Transpose swaps rows and columns.

In [24]:
print(matrix)
print()
print(matrix.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


### Matrix Multiplication
- Use the "@" operator or "np.matmul()".

In [25]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])
matrix2 = np.array([
    [5, 6],
    [7, 8]
])
print(matrix1 @ matrix2)

[[19 22]
 [43 50]]


### Save an Array
- Save a NumPy array to a file using 'save()'.

In [26]:
numbers = np.array([10, 20, 30, 40])
np.save('numbers.npy', numbers)

### Load an Array
- Read a saved array using 'load()'

In [27]:
numbers = np.load('numbers.npy')
print(numbers)

[10 20 30 40]


### Why Use NumPy?
- Fast numerical computations
- Efficient memory usage
- Easy array manipulation
- Built-in mathematical functions
- Foundation for Pandas, SciPy, Scikit-learn, TensorFlow and many other libraries.

# File Handling & Exception Handling
Real-world applications need to store and manage data. That's where file handling becomes important.

## What is File Handling?  

- File handling allows Python to:
1. Read data from files
2. Write data into files
3. Store information permenently

## Opening a File
Use **open()** to work with files.

> Example:
file = open('data.txt', 'r')

- **'r'** means read mode

## Reading a File

In [1]:
file = open('data.txt', 'r')
content = file.read()
print(content)
file.close()

Hello! This is an example text for this file.

More lines added to this file.

These make the file longer and easier to work with.



## Read Line by Line

In [2]:
file = open('data.txt', 'r')
for line in file:
    print(line)
file.close()

Hello! This is an example text for this file.



More lines added to this file.



These make the file longer and easier to work with.



## Writing to a File
- Use **'w'** mode to write data.

In [3]:
file = open('notes.txt', 'w')
file.write('Python File Handling')
file.close() # 'w' overwrites existing data

## Appending Data
- Use **'a'** mode to add data without deleting old content

In [4]:
file = open('notes.txt', 'a')
file.write('\nNew Line Added')
file.close()

## Using **with** Statement
Best way to handle files
1. Automatically closes the file
2. Cleaner and safer code

In [5]:
with open('data.txt', 'r') as file:
    content = file.read()
    print(content)

Hello! This is an example text for this file.

More lines added to this file.

These make the file longer and easier to work with.



## Working with CSV Files and Exception Handling
- CSV files are used for tabular data.

### What is Exception Handling?
- Errors can crash programs.
- Exception handling prevents that

In [8]:
import csv
try:
    with open('data.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            print(row)
except:
    print('File does not exist!!!')

File does not exist!!!


In [9]:
# Handling Specific Errors
try:
    result = 10 / 0
except ZeroDivisionError:
    print('Cannot divide by zero')

Cannot divide by zero


## Finally Block
- **finally** always runs whether error occurs or not.

In [10]:
try:
    print('Start')
except:
    print('Error')
finally:
    print('Finished')

Start
Finished


# Object-Orientend Programming (OOP)
- Object-Oriented Programming (OOP) in one of the most important concepts in Python.
- Almost every real world Python application uses OOP concepts.

## What is OOP?
- OOP is a programming approach that organizes code into objects
  
**Each object has:**
- Properties (Data)
- Behavior (Fuctions)

## What is a Class?
- A class is a blueprint for creating objects

**Example:**
class Car:

- Here, 'Car' is a class

## Creating an Object
- An object is an instance of a class:

In [11]:
class Car:
    pass

car1 = Car()
print(type(car1))

<class '__main__.Car'>


## Attributes in a Class
- Attributes store information

In [12]:
class Car:
    brand = 'Toyota'

car1 = Car()
print(car1.brand)

Toyota


## Constructor ('init')
- A constructor runs automatically when an object is created.

In [13]:
class Car:
    def __init__(self, brand):
        self.brand = brand

car1 = Car('Toyota')
print(car1.brand)

Toyota


## Instance Methods
- Methods define object behavior

In [14]:
class Car:
    def start(self):
        print('Car Started')

car1 = Car()
car1.start()

Car Started


## Inheritance
- Inheritance allows one class to use features of another class.

In [16]:
class Vehicle:
    def moves(self):
        print('Vehicle Moving')

class Car(Vehicle):
    pass

car1 = Car()
car1.moves()

Vehicle Moving


## Encapsulation
- Encapsulation hides data from direct access.

In [17]:
class Account:
    def __init__(self):
        self.__balance = 1000 # private variable

account = Account()

## Polymorphism
- Same method name, different behavior.

In [18]:
class Bird:
    def sound(self):
        print('Bird Sound')

class Dog:
    def sound(self):
        print('Dog Sound')

bird = Bird()
dog = Dog()

bird.sound()
dog.sound()

Bird Sound
Dog Sound


## Method Overriding
- Child class can redefine a parent method.

In [21]:
class Vehicle:
    def moves(self):
        print('Vehicle Moving')

class Bike(Vehicle):
    def moves(self):
        print('Bike Moving')

bike = Bike()
bike.moves()

Bike Moving


# What is an API?
- API stands fro Application Programming Interface.
- An API allows different applications to communicate with each other.
  
**Examples**
1. Weather Apps
2. Payment Gateways
3. Mobile Applications
4. AI Applications

## Working with APIs
- The most popular library for API requests is 'requests'.

In [2]:
import requests

# response = requests.get('https://api.example.com/data')

# print(response.status_code)

- 200 means the request was successful

## Understanding JSON Data
- Most API return data in JSON format

**Example JSON:**  
{
    'product': 'Laptop',
    'price': 50000,
    'available': true
}

In [3]:
# Convert JSON into Python'
data = response.json()
print(data)

NameError: name 'response' is not defined

## What is Web Scraping?
- Web Scraping mean extractind data from websites automatically

**Used for:**
1. Price Tracking
2. News Collection
3. Job Listings
4. Research Projects

**Popular Libraries:** BeautifulSoup, requests

## Simple Web Scraping Example

In [ ]:
import requests
from bs4 import BeautifulSoup
page = requests.get('https://example.com')
soup = BeautifulSoup(page.text, 'html.parser')
print(soup.title.text)
# This extract the webpage title.

## Important Note About Web Scraping
- Always:
1. Read website policies
2. Respect rate limits
3. Avoid excessive requests
4. Use scraping responsibly
- Some websites prohibit automated scraping

# Pandas

## What is Pandas?
- Pandas is an open-source Python library used for:
1. Data Analysis
2. Data Cleaning
3. Data Transformation
4. Data Exploration
5. Working with Excel and CSV files
- It helps you organize and analyze structured data efficiently

## What is a Series?
- A Series is a one-demensional data structure

In [1]:
import pandas as pd
numbers = pd.Series([10, 20, 30, 40])

print(numbers)

0    10
1    20
2    30
3    40
dtype: int64


## What is a DataFrame?
- A DataFrame is a table with rows and columns

In [2]:
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet'],
    'Price': [50000, 25000, 18000]
}

df = pd.DataFrame(data)

print(df)

  Product  Price
0  Laptop  50000
1  Mobile  25000
2  Tablet  18000


## Read a CSV File
- Use read_csv() to load CSV files.

In [3]:
df = pd.read_csv('sales.csv')
print(df)

  Product  Sales
0       A    100
1       B    150
2       C    200
3       A    120
4       B    180
5       C    220


- Pandas automatically converts the CSV into a DataFrame.

## View Data

In [4]:
# Display the first five rows
print(df.head())

# Display the last five rows
print(df.tail())

# Check the size of the dataset
print(df.shape)

# Display column names
print(df.columns)

  Product  Sales
0       A    100
1       B    150
2       C    200
3       A    120
4       B    180
  Product  Sales
1       B    150
2       C    200
3       A    120
4       B    180
5       C    220
(6, 2)
Index(['Product', 'Sales'], dtype='str')


# Selecting Data, Rows & Columns with Examples
- Selecting the right data is one of the most frequently used skills in Pandas.

## Create a Sample DataFrame
- We'll use this DataFrame throughout the examples.

In [1]:
import pandas as pd

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Monitor'],
    'Price': [50000, 25000, 18000, 12000],
    'Stock': [10, 25, 15, 8]
}

df = pd.DataFrame(data)

print(df)

   Product  Price  Stock
0   Laptop  50000     10
1   Mobile  25000     25
2   Tablet  18000     15
3  Monitor  12000      8


## Select a Single Column
- Use the column name to access one column

In [2]:
print(df['Product'])

0     Laptop
1     Mobile
2     Tablet
3    Monitor
Name: Product, dtype: str


## Select Multiple Columns
- Pass a list of column names.

In [3]:
print(df[['Product', 'Price']])

   Product  Price
0   Laptop  50000
1   Mobile  25000
2   Tablet  18000
3  Monitor  12000


## Select Rows using **loc[]**
- **loc[]** selects rows using labels (index values)

In [4]:
print(df.loc[2])

Product    Tablet
Price       18000
Stock          15
Name: 2, dtype: object


## Select Rows using **iloc[]**
- **iloc[]** selects rows using their position.

In [6]:
print(df.iloc[1:3])

  Product  Price  Stock
1  Mobile  25000     25
2  Tablet  18000     15


## Filter Data
- Display only products with a price greater than 20,000

In [7]:
print(df[df['Price'] > 20000])

  Product  Price  Stock
0  Laptop  50000     10
1  Mobile  25000     25


## Sort Data

In [8]:
# Sort products by price in ascending order
print(df.sort_values('Price'))

   Product  Price  Stock
3  Monitor  12000      8
2   Tablet  18000     15
1   Mobile  25000     25
0   Laptop  50000     10


In [9]:
# Sort in descending order
print(df.sort_values('Price', ascending=False))

   Product  Price  Stock
0   Laptop  50000     10
1   Mobile  25000     25
2   Tablet  18000     15
3  Monitor  12000      8


# Data Cleaning, Missing Values & Duplicates
- Real-world datasets are rarely perfect.
- Before analyzing data, you need to clean in. Data cleaning is one of the most important tasks for every Data Analyst and Data Scientist.

## What are Missing Values?
- Missing values occur when some data is unavailable.

In [10]:
import pandas as pd

data = {
    'Product': ['Laptop','Mobile', None, 'Tablet'],
    'Price': [50000, None, 18000, 15000]
}

df = pd.DataFrame(data)

print(df)

  Product    Price
0  Laptop  50000.0
1  Mobile      NaN
2     NaN  18000.0
3  Tablet  15000.0


- 'NaN' means Not a Number, indicating a missing value

## Detect Missing Values
- Use **isnull()** to identify missing values.

In [11]:
print(df.isnull())

   Product  Price
0    False  False
1    False   True
2     True  False
3    False  False


In [12]:
# Count missing values in each column
print(df.isnull().sum())

Product    1
Price      1
dtype: int64


## Remove Missing Values
- Use **dropna()** to remove rows with missing values.

In [13]:
clean_df = df.dropna()
print(clean_df)

  Product    Price
0  Laptop  50000.0
3  Tablet  15000.0


## Fill Missing Values
- Instead of deleting rows, you can replace missing values.

In [14]:
# Replace missing prices with 0
df['Price'] = df['Price'].fillna(0)

# Replace missing product names
df['Product'] = df['Product'].fillna('Unknown')

print(df)

   Product    Price
0   Laptop  50000.0
1   Mobile      0.0
2  Unknown  18000.0
3   Tablet  15000.0


## Find Duplicate Rows
- Use **duplicate()** to identify duplicat records.

In [15]:
print(df.duplicated())

0    False
1    False
2    False
3    False
dtype: bool


- If a row is repeated, it wil return **True**

## Remove Duplicate Rows
- Use **drop_duplicates()**

In [16]:
df = df.drop_duplicates()
print(df)

   Product    Price
0   Laptop  50000.0
1   Mobile      0.0
2  Unknown  18000.0
3   Tablet  15000.0


- This keeps only unique records

## Check Data Information
- Use **info()** to understand your dataset.

In [17]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Product  4 non-null      str    
 1   Price    4 non-null      float64
dtypes: float64(1), str(1)
memory usage: 196.0 bytes
None


## Generate Summary Statistics
- Use **describe()** to get statistical information.

In [18]:
print(df.describe())

              Price
count      4.000000
mean   20750.000000
std    21029.740845
min        0.000000
25%    11250.000000
50%    16500.000000
75%    26000.000000
max    50000.000000


**Pro Tip**
- A good data analyst always follows this order:
1. Load the dataset
2. Check **head()**
3. Check **info()**
4. Find missing values
5. Remove duplicates
6. Start the analysis

# GroupBy, Aggregation & Data Analysis
- One of the biggest strengths of Pandas is its ability to summarize large datasets with just a few lines of code.

## Create a Sample DataFrame
- We'll use this dataset throughout the examples

In [1]:
import pandas as pd

data = {
    'Department': ['Sales', 'IT', 'Sales', 'HR', 'IT', 'HR'],
    'Salary': [50000, 70000, 55000, 45000, 75000, 48000],
    'Experience': [2, 5, 3, 1, 6, 2]
}

df = pd.DataFrame(data)
print(df)

  Department  Salary  Experience
0      Sales   50000           2
1         IT   70000           5
2      Sales   55000           3
3         HR   45000           1
4         IT   75000           6
5         HR   48000           2


## What is GroupBy?
- **groupby()** groups rows having the same value.

In [2]:
print(df.groupby('Department'))

- This creates groups based on the Department column.

## Calculate Average Salary
- Find the average salary for each department

In [3]:
print(df.groupby('Department')['Salary'].mean())

Department
HR       46500.0
IT       72500.0
Sales    52500.0
Name: Salary, dtype: float64


## Calculate Average Salary
- Find the average salary for each department

In [4]:
print(df.groupby('Department')['Salary'].sum())

Department
HR        93000
IT       145000
Sales    105000
Name: Salary, dtype: int64


## Multiple Aggregation Functions
- Calculate multiple statistics at once.

In [6]:
print(
    df.groupby('Department')['Salary'].agg(['sum','mean', 'max','min', 'std'])
)

               sum     mean    max    min          std
Department                                            
HR           93000  46500.0  48000  45000  2121.320344
IT          145000  72500.0  75000  70000  3535.533906
Sales       105000  52500.0  55000  50000  3535.533906


## Count Records
- Count the number of records in each department

In [7]:
print(df.groupby('Department').size())

Department
HR       2
IT       2
Sales    2
dtype: int64


## Count Unique Values
- Use **value_counts()** to count occurrences.

In [8]:
print(df['Department'].value_counts())

Department
Sales    2
IT       2
HR       2
Name: count, dtype: int64


## Find Unique Values
- Display unique department names.

In [9]:
print(df['Department'].unique())

<StringArray>
['Sales', 'IT', 'HR']
Length: 3, dtype: str


## Sort Aggregated Results
- Sort departments by average salary.

In [11]:
result = df.groupby('Department')['Salary'].mean()
print(result.sort_values(ascending=False))

Department
IT       72500.0
Sales    52500.0
HR       46500.0
Name: Salary, dtype: float64


## Practice Exercises

In [12]:
# Find the average salary for each department
print(df.groupby('Department')['Salary'].mean())

Department
HR       46500.0
IT       72500.0
Sales    52500.0
Name: Salary, dtype: float64


In [13]:
# Find the highest salary in each department
print(df.groupby('Department')['Salary'].max())

Department
HR       48000
IT       75000
Sales    55000
Name: Salary, dtype: int64


In [16]:
# count employees in each department
print(df.groupby('Department').size())

Department
HR       2
IT       2
Sales    2
dtype: int64


In [20]:
# Display unique department names
print(df['Department'].unique())

<StringArray>
['Sales', 'IT', 'HR']
Length: 3, dtype: str


In [22]:
# Sort departments by average salary in descending order
print(df.groupby('Department')['Salary'].mean().sort_values(ascending=False))

Department
IT       72500.0
Sales    52500.0
HR       46500.0
Name: Salary, dtype: float64


# Merge, Join, Concatenate & Pivot Tables with Examples
- In real-world projects, your data is often spread across multiple files or tables.
- Pandas provide powerful functions to combine and summarize data efficiently.

- In this part, you'll learn:
1. Merge DataFrames
2. Join DataFrames
3. Concatenate DataFrames
4. Pivot Tables
5. CrossTab
6. Real-World Use Cases

## Create Sample DataFrames
- We'll use these DataFrames throughout the examples.

In [24]:
import pandas as pd

products = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'Product': ['Laptop', 'Mobile', 'Tablet']
})

sales = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'Sales': [120, 250, 180]
})

## Merge DataFrames
- Use "merge()" to combine DataFrames based on a common column.

In [25]:
result = pd.merge(products, sales, on='ProductID')
print(result)

   ProductID Product  Sales
0        101  Laptop    120
1        102  Mobile    250
2        103  Tablet    180


## Join DataFrames
- Use "join()" to combine DataFrames using their indexes.

In [26]:
result = products.join(sales['Sales'])
print(result)

   ProductID Product  Sales
0        101  Laptop    120
1        102  Mobile    250
2        103  Tablet    180


## Concatenate DataFrames
- Use "concat()" to combine DataFrames vertically.

In [27]:
first = pd.DataFrame({
    'Value': [10, 20]
})
second = pd.DataFrame({
    'Value': [30, 40]
})
result = pd.concat([first, second])
print(result)

   Value
0     10
1     20
0     30
1     40


## Create a Pivot Table
- A Pivot Table summarizes data quickly.

In [28]:
data = pd.DataFrame({
    'Department': ['Sales', 'Sales', 'IT', 'IT'],
    'Salary': [50000, 55000, 70000, 75000]
})
pivot = data.pivot_table(
    values='Salary',
    index='Department',
    aggfunc='mean'
)
print(pivot)

             Salary
Department         
IT          72500.0
Sales       52500.0


## Create a Crosstab
- A crosstab counts the frequency of combinations between columns.

In [29]:
data = pd.DataFrame({
    'Department': ['Sales', 'Sales', 'IT', 'HR'],
    'Shift': ['Morning', 'Evening', 'Morning', 'Evening']
})
print(pd.crosstab(data['Department'],data['Shift']))

Shift       Evening  Morning
Department                  
HR                1        0
IT                0        1
Sales             1        1


**Pro Tip**
- Remember this rule:
1. 'merge()' - Combine using common columns
2. 'join()' - Combine using indexes
3. 'concat()' - Stack DataFrame vertically
4. 'pivot_table()' - Summarize data
5. 'crosstab()' - Count combinations

In [31]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

print(pd.concat([df1, df2]))

     A    B
0  1.0  NaN
1  2.0  NaN
0  NaN  3.0
1  NaN  4.0
