# WhatsApp Data Analysis and AI journey

## What is Numpy?  
- Numpy Numerical Python is a powerful Python library used for working with numbers and arrays.

## Why Use Numpy?
- Python lists work well, but Numpy arrays are much faster for mathematical operations
- Numpy is used for:
1. Data Analysis
2. Machine Learning
3. Data Visualization
4. Scientific Computing

In [1]:
# Importing the library
import numpy as np

In [2]:
# Creating numpy arrays
numbers = np.array([10, 20, 30, 40])
print(numbers)

[10 20 30 40]


In [4]:
# Check Array Properties
print(numbers.ndim) # Number of dimentions
print(numbers.size) # Total number of elements
print(numbers.shape) # Structure of the array

1
4
(4,)


In [5]:
# Accessing Array Elements
print(numbers[0])
print(numbers[2])

10
30


In [6]:
# Array Slicing
print(numbers[1:4])

[20 30 40]


In [7]:
# Basic Array Operations
print(numbers + 5)
print(numbers * 2)

[15 25 35 45]
[20 40 60 80]


- Numpy performs operations on every element at once (elementwise operation)

In [10]:
# Print the first and last element
print(numbers[-1])
print(numbers[0])

# Add 100 to every element
print(numbers + 100)

40
10
[110 120 130 140]


## Master 2D Arrays, Reshaping & Mathematical Functions  

### What is a 2D Array?
- A 2D array stores data in rows and columns, just like a table or spreadsheet

In [11]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(matrix)

[[10 20 30]
 [40 50 60]]


In [13]:
# Check Array Shape
# Use the .shape attribute to find the dimensions of an array

print(matrix.shape) # 2 row and 3 columns

(2, 3)


In [14]:
# Reshape an Array
# Convert a 1D array into a 2D array using .reshape()
numbers = np.array([1, 2, 3, 4, 5, 6])

new_array = numbers.reshape(2, 3)
print(new_array)

[[1 2 3]
 [4 5 6]]


- The total number of elements must remain the same

## Mathematical Functions
- NumPy provides built-in functions for calculations

In [15]:
numbers = np.array([10, 20, 30, 40])

print(np.sum(numbers))
print(np.mean(numbers))

100
25.0


In [16]:
# Minimum and Maximum Values
numbers = np.array([25, 10, 45, 30])

print(np.min(numbers))
print(np.max(numbers))

10
45


In [17]:
# Mean, Median & Standard Deviation
# These are common statistical calculations
numbers = np.array([10, 20, 30, 40])

print(np.mean(numbers)) # Average value
print(np.median(numbers)) # Middle value after sorting
print(np.std(numbers)) # Measures how spread out the values are

25.0
25.0
11.180339887498949


In [18]:
matrix.size

6

## Indexing, Slicing, Boolean Indexing and Filtering
- One of the biggest advantages of NumPy is how quickly you can access and filter data.

### Array Indexing
- Indexing is used to access a specific element in an array.

In [2]:
import numpy as np
numbers = np.array([10, 20, 30, 40, 50, 60])

# Indexing starts from 0
print(numbers[0])
print(numbers[3])

10
40


### Array Slicing
- Slicing extracts a portion of an array

In [4]:
print(numbers[1:5])
print(numbers[:3])
print(numbers[3:])
print(numbers[-2:])

[20 30 40 50]
[10 20 30]
[40 50 60]
[50 60]


### Indexing in 2D Arrays
- Access elements using row and column indexes.

In [5]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix[1, 2])

60


In [6]:
# Access an entire row:
print(matrix[0])

# Access an entire column
print(matrix[:, 1])

[10 20 30]
[20 50 80]


### Boolean Indexing
- Boolean indexing selects elements that satisfy a condition.

In [8]:
numbers = np.array([12, 25, 8, 40, 15])
print(numbers > 20)

[False  True False  True False]


### Filtering Data
- Use Boolean indexing to filter values.

In [9]:
print(numbers[numbers > 20])

[25 40]


In [11]:
print(numbers[numbers % 2 == 0])

[12  8 40]


### Multiple Conditions
- Filter using more than one condition.

In [12]:
numbers = np.array([12, 25, 8, 40, 15, 30])
result = numbers[(numbers >= 15) & (numbers <= 30)]
print(result)

[25 15 30]
